export { default as SEO } from './seo'
export { default as Header, WorkPageHeader } from './header'
export { default as Footer } from './footer'
export { default as Section } from './section'
export { default as Grid } from './grid'
export { default as About } from './about'
export { default as Form } from './Form/Form'
export { default as ContactInfo } from './contact-info'
export { default as ProjectFullscreen } from './projectFullscreen'