export { default as Banner } from './banner'
export { default as Works } from './works'
export { default as Project } from './project'
export { default as Quote } from './quote'
export { default as Contact } from './contact'